apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart-wikimedia.fullname" . }}
  labels:
    {{- include "helm-chart-wikimedia.labels" . | nindent 4 }}
data:
  000-default.conf: |
    <VirtualHost *:80>
      #ServerName www.example.com
      ServerAdmin webmaster@localhost
      DocumentRoot /var/www/html/wikimedia
      <Directory "/var/www/html/wikimedia">
      DirectoryIndex index.html index.html.var index.php
      </Directory>
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>